version: "3.9"

services:
  bookswap:
    container_name: bookswap
    build: .
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/app
    ports:
      - 8000:80
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookswap
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bookswap
    expose: 
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bookswap -d bookswap" ]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true

volumes:
  postgres_data: